FROM ubuntu

ARG BOT_TOKEN
ARG DB_PASSWORD
ARG DB_PORT
ARG DB_USER
ARG DB_HOST
ARG DB_NAME

ENV BOT_TOKEN=${BOT_TOKEN}
ENV DB_PASSWORD = ${DB_PASSWORD}
ENV DB_PORT = ${DB_PORT}
ENV DB_USER = ${DB_USER}
ENV DB_HOST = ${DB_HOST}
ENV DB_NAME = ${DB_NAME}

#INSTALL CA-CERTS
RUN apt -q update && apt install -qy ca-certificates
RUN update-ca-certificates
#COPY BINARY
COPY main .
CMD ["./main"]